module.exports = {
	MAP_CELL_COUNT: 560,
	MAX_LEVEL: 200,
	MAX_GUILD_LEVEL: 200,
	MAX_MOUNT_LEVEL: 100,
	MAX_CHAT_LEN: 512,
	USER_MAX_CHAT_LEN: 256,
	MIN_LOGIN_LEN: 3,
	MAX_LOGIN_LEN: 50,
	MIN_PLAYER_NAME_LEN: 2,
	MAX_PLAYER_NAME_LEN: 20,
	MIN_NICK_LEN: 2,
	MAX_NICK_LEN: 30,
	MIN_GUILDNAME_LEN: 3,
	MAX_GUILDNAME_LEN: 30,
	MIN_ALLIANCENAME_LEN: 3,
	MAX_ALLIANCENAME_LEN: 30,
	MIN_ALLIANCETAG_LEN: 3,
	MAX_ALLIANCETAG_LEN: 5,
	MAX_PLAYER_COLOR: 5,
	MAX_ENTITY_COLOR: 8,
	MAX_PLAYERS_PER_TEAM: 8,
	MAX_MEMBERS_PER_PARTY: 8,
	MAX_GUESTS_PER_PARTY: 7,
	MAX_MEMBERS_PER_ARENA_PARTY: 5,
	MAX_MONSTERS_IN_GROUP_ON_MAP: 16,
	MAX_CHAT_OBJECT_REF: 16,
	NOT_EQUIPED: 63,
	MAX_EQUIPED: 255,
	MAX_JOBS_PER_CHARACTER: 6,
	MAX_CRAFT_SLOT: 9,
	MAX_JOB_LEVEL: 100,
	MAX_HONOR: 20000,
	MAX_SHORTCUT: 99,
	MAX_ARENA_RANK: 2300,
	CHAR_MIN_LEVEL_ARENA: 50,
	CHAR_MIN_LEVEL_RIDE: 60,
	MAX_DUNGEON_REGISTER: 10,
	MIN_RIDE_NAME_LEN: 0,
	MAX_RIDE_NAME_LEN: 16,
	MAX_EFFECTS_COUNT: 100,
	MAX_LOCKABLE_CODE_LEN: 8,
	MAX_PRESET_ITEM_COUNT: 24,
	MIN_OBJ_COUNT_BY_XFERT: 1,
	MAX_OBJ_COUNT_BY_XFERT: 1000,
	MAX_OBJECT_EFFECT_STRING_LEN: 30,
	MAX_PLAYER_OR_ACCOUNT_NAME_LEN: 31,

	// Constants below were not found in Flash constants; added "by hand"
	MAX_NUMBER: 2000000000, // 9 zeros - used for prices too
	MAX_NUMBER_LEN: 13      // 2,000,000,000 = 13 chars (MAX_NUMBER + formatting)
};



/*****************
 ** WEBPACK FOOTER
 ** ./src/views/common/protocolConstants/index.js
 ** module id = 211
 ** module chunks = 0
 **/